//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arsiv_Projesi {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Arsiv_Projesi.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOG IN.
        /// </summary>
        internal static string LoginButtonLogin {
            get {
                return ResourceManager.GetString("LoginButtonLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Fields.
        /// </summary>
        internal static string LoginLabelClearFields {
            get {
                return ResourceManager.GetString("LoginLabelClearFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string LoginLabelExit {
            get {
                return ResourceManager.GetString("LoginLabelExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOG IN.
        /// </summary>
        internal static string LoginLabelLogin {
            get {
                return ResourceManager.GetString("LoginLabelLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Archive Room.
        /// </summary>
        internal static string String1ToolStripMenuItemAddArchiveRoom {
            get {
                return ResourceManager.GetString("String1ToolStripMenuItemAddArchiveRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive Room.
        /// </summary>
        internal static string ToolStripMenuItemArchiveRoom {
            get {
                return ResourceManager.GetString("ToolStripMenuItemArchiveRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Archive Room.
        /// </summary>
        internal static string ToolStripMenuItemDeleteArchiveRoom {
            get {
                return ResourceManager.GetString("ToolStripMenuItemDeleteArchiveRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Archive Room.
        /// </summary>
        internal static string ToolStripMenuItemListArchiveRoom {
            get {
                return ResourceManager.GetString("ToolStripMenuItemListArchiveRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Archive Room.
        /// </summary>
        internal static string ToolStripMenuItemSearchArchiveRoom {
            get {
                return ResourceManager.GetString("ToolStripMenuItemSearchArchiveRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Archive Room.
        /// </summary>
        internal static string ToolStripMenuItemUpdateArchiveRoom {
            get {
                return ResourceManager.GetString("ToolStripMenuItemUpdateArchiveRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WELCOME.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
